version: "3.8"
services:
  app:
    build:
      context: .
    container_name: filter_on_price
    env_file: .env
    restart: always
    volumes:
      - ./src:/app
    ports:
      - "5002:5000"
    command: python main.py
